#!/bin/bash
APP="demoCodePipeline"
pm2 describe ${APP} > /dev/null
RUNNING=$?

if [ "${RUNNING}" -ne 0 ]; then
  pm2 start /opt/demoCodePipeline/worker.js --name ${APP} -i 2 --log-date-format="YYYY-MM-DD HH:mm Z"
else
  pm2 reload ${APP} --log-date-format="YYYY-MM-DD HH:mm Z"
fi